# Generated by Django 2.2 on 2019-08-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome Completo')),
                ('nome_usuario', models.CharField(max_length=30, verbose_name='Login de Usuario')),
                ('data_inicio', models.DateField(verbose_name='Data Inicio')),
                ('data_fim', models.DateField(verbose_name='Data Termino')),
                ('setor', models.CharField(max_length=30, verbose_name='Setor')),
                ('ramal', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Ramal')),
            ],
        ),
        migrations.AlterField(
            model_name='produto',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='hora',
            field=models.TimeField(verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default=1, upload_to='produto_img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
    ]
