# Generated by Django 2.2 on 2019-08-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20190801_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='ramal',
            field=models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Ramal'),
        ),
    ]
