# Generated by Django 2.2 on 2019-08-01 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_auto_20190801_1444'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
