# Generated by Django 2.2 on 2019-08-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('nome_usuario', models.CharField(max_length=30, verbose_name='Nome')),
                ('email',models.CharField(verbose_name='Email')),
                ('data_inicio', models.DateField(verbose_name='Data Inicio')),
                ('data_fim', models.DateField(verbose_name='Data Final')),
                ('setor', models.CharField(max_length=20, verbose_name='Setor')),
                ('ramal', models.IntegerField(verbose_name='Ramal')),
            ],
        ),
    ]
