# Generated by Django 2.2 on 2019-08-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='nome_usuario',
            field=models.CharField(max_length=30, verbose_name='Usuário'),
        ),
    ]
