# Generated by Django 2.2.3 on 2019-08-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20190802_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.CharField(max_length=40, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome Completo'),
        ),
    ]
